"""Recognition pipeline tests against deterministic SYNTHETIC fixtures
(tests/fixtures/*.png, generated by scripts/gen_recognition_fixtures.py).

These are clearly synthetic verification images with known ground truth,
NOT real Meowdoku screenshots -- see README for why, and for how to
exercise the pipeline against a real screenshot if one becomes available.
Region partitions are compared independently of arbitrary region-label
numbering, since the clustering algorithm has no reason to assign the same
integer ids as the fixture generator used.
"""
from __future__ import annotations

import json
from pathlib import Path

import cv2
import numpy as np
import pytest

from meowdoku.models import CellState
from meowdoku.recognition import pipeline

FIXTURES_DIR = Path(__file__).parent / "fixtures"
FIXTURE_NAMES = ["basic_5x5", "noisy_6x6", "large_cells_4x4", "offset_crop_7x7"]


def partitions_equal(grid_a, grid_b, size) -> bool:
    """True if two region-id grids describe the same partition of cells
    into groups, regardless of which integer label each group was given."""
    for r1 in range(size):
        for c1 in range(size):
            for r2 in range(size):
                for c2 in range(size):
                    if (grid_a[r1][c1] == grid_a[r2][c2]) != (grid_b[r1][c1] == grid_b[r2][c2]):
                        return False
    return True


def load_fixture(name):
    img = cv2.imread(str(FIXTURES_DIR / f"{name}.png"))
    with open(FIXTURES_DIR / f"{name}.ground_truth.json") as f:
        gt = json.load(f)
    return img, gt


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_recognizes_board_size(name):
    img, gt = load_fixture(name)
    result = pipeline.recognize(img)
    assert result.success, result.warnings
    assert result.grid.size == gt["size"]


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_region_partition_matches_ground_truth_independent_of_labels(name):
    img, gt = load_fixture(name)
    result = pipeline.recognize(img)
    assert result.success
    assert partitions_equal(result.board.region_ids, gt["region_ids"], result.grid.size)


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_cat_and_x_marks_are_detected_at_the_right_cells(name):
    img, gt = load_fixture(name)
    result = pipeline.recognize(img)
    assert result.success
    board = result.board
    for key, kind in gt["cell_states"].items():
        r, c = map(int, key.split(","))
        state = board.cell_states[r][c]
        if kind == "cat":
            assert state in (CellState.CAT_CONFIRMED, CellState.CAT_UNCERTAIN), f"{name} {key} expected a cat, got {state}"
        elif kind == "x":
            assert state == CellState.X_MARK, f"{name} {key} expected an X mark, got {state}"

    marked_cells = {(r, c) for r in range(board.size) for c in range(board.size) if board.cell_states[r][c] != CellState.EMPTY}
    expected_cells = {tuple(map(int, key.split(","))) for key in gt["cell_states"]}
    assert marked_cells == expected_cells, f"{name}: unexpected extra or missing marks {marked_cells ^ expected_cells}"


def test_empty_capture_is_a_recognition_failure_not_a_crash():
    blank = np.zeros((300, 300, 3), dtype=np.uint8)
    result = pipeline.recognize(blank)
    assert not result.success
    assert result.failure_reason == "empty_capture"


def test_tiny_capture_is_reported_as_clipped_not_a_crash():
    tiny = np.random.randint(0, 255, (10, 10, 3), dtype=np.uint8)
    result = pipeline.recognize(tiny)
    assert not result.success
    assert result.failure_reason == "clipped_grid"


def test_featureless_capture_reports_no_grid_found():
    # Random static has real pixel variance (so it is not classified as an
    # "empty_capture" blank), but no grid-like periodic edge structure at
    # all, so no plausible board size can be estimated -- must fail cleanly
    # with a distinct reason, not guess some N.
    rng = np.random.RandomState(0)
    static = rng.randint(0, 255, (200, 200, 3), dtype=np.uint8)
    result = pipeline.recognize(static)
    assert not result.success
    assert result.failure_reason == "no_grid_found"


def test_region_count_mismatch_is_flagged_for_review_not_silently_forced():
    img, gt = load_fixture("basic_5x5")
    # Force an override to a size that does not match the true region count,
    # simulating a wrong board-size override or a genuinely ambiguous crop.
    result = pipeline.recognize(img, size_override=3)
    assert result.success
    assert result.needs_review
    assert any("region" in w.lower() for w in result.warnings)


def test_size_override_is_respected_even_if_auto_detection_would_differ():
    img, gt = load_fixture("basic_5x5")
    result = pipeline.recognize(img, size_override=5)
    assert result.success
    assert result.grid.size == 5
